<?php

namespace App\Filament\Resources\Usuarios\Schemas;

use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Schemas\Schema;

class UsuarioForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('tipo')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('nome')
                    ->required(),
                TextInput::make('email')
                    ->label('Email address')
                    ->email()
                    ->required(),
                TextInput::make('senha')
                    ->required(),
                TextInput::make('salt')
                    ->required(),
                TextInput::make('email_confirmado')
                    ->email()
                    ->required()
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('datacad')
                    ->required(),
                TextInput::make('email_checkstring')
                    ->email()
                    ->required(),
                DateTimePicker::make('session_date')
                    ->required(),
                TextInput::make('tentativas_erradas')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('imagem')
                    ->required()
                    ->default('https://static.inscricoes.bike/assets/img/default-avatar.jpg'),
                DateTimePicker::make('datasenha')
                    ->required(),
                TextInput::make('telefone')
                    ->tel()
                    ->required(),
                TextInput::make('cidade')
                    ->required(),
                TextInput::make('estado')
                    ->required(),
                DateTimePicker::make('data_nascimento')
                    ->required(),
                TextInput::make('hashh')
                    ->required(),
                DateTimePicker::make('data_confirmacao')
                    ->required(),
                TextInput::make('cpf')
                    ->required(),
                TextInput::make('uf')
                    ->required(),
                TextInput::make('primeiroevento')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('email_recover')
                    ->email()
                    ->required(),
                Textarea::make('useragent')
                    ->columnSpanFull(),
                TextInput::make('screenwidth')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('ipregistro')
                    ->required(),
                TextInput::make('instagram')
                    ->required(),
                TextInput::make('sexo')
                    ->required(),
                TextInput::make('numerocbc')
                    ->required(),
                TextInput::make('nomeequipe')
                    ->required(),
                TextInput::make('nomepai')
                    ->required(),
                TextInput::make('nomemae')
                    ->required(),
                TextInput::make('endereco')
                    ->required(),
                TextInput::make('rg')
                    ->required(),
                TextInput::make('bairro')
                    ->required(),
                TextInput::make('cep')
                    ->required(),
                TextInput::make('sangue')
                    ->required(),
                TextInput::make('categoria')
                    ->required(),
                TextInput::make('naturalidade')
                    ->required(),
                TextInput::make('altura')
                    ->required(),
                TextInput::make('tcalcado')
                    ->required(),
                TextInput::make('tagasalho')
                    ->required(),
                TextInput::make('tcamiseta')
                    ->required(),
                TextInput::make('tshort')
                    ->required(),
                Textarea::make('creditos')
                    ->columnSpanFull(),
                TextInput::make('evtbike')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('evtcorrida')
                    ->required()
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('dtCadastroAtualizado')
                    ->required(),
                TextInput::make('apelido')
                    ->required(),
                TextInput::make('filiado2024')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('qtdEventos')
                    ->required()
                    ->numeric()
                    ->default(0),
            ]);
    }
}
