<?php

namespace App\Filament\Resources\Eventos\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class EventoInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('organizador')
                    ->numeric(),
                TextEntry::make('active')
                    ->numeric(),
                TextEntry::make('tipoevento')
                    ->numeric(),
                TextEntry::make('titulo')
                    ->placeholder('-'),
                TextEntry::make('descricao')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('dataevento')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('horaevento')
                    ->placeholder('-'),
                TextEntry::make('horafinal'),
                TextEntry::make('horafinalprovavel'),
                TextEntry::make('localevento')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('premiacao')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('roteiro')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('precovlr')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('precodescr')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('outrasinformacoes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('banner')
                    ->placeholder('-'),
                TextEntry::make('url'),
                TextEntry::make('qtdinscritos')
                    ->numeric(),
                TextEntry::make('mapa')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('cidade')
                    ->placeholder('-'),
                TextEntry::make('uf')
                    ->placeholder('-'),
                TextEntry::make('cep'),
                TextEntry::make('historico')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('sessoes')
                    ->numeric(),
                TextEntry::make('pageviews')
                    ->numeric(),
                TextEntry::make('prices')
                    ->numeric(),
                TextEntry::make('acceptpagseguro')
                    ->numeric(),
                TextEntry::make('urlcompleta'),
                TextEntry::make('netValue')
                    ->numeric(),
                TextEntry::make('paidSubscriptions')
                    ->numeric(),
                TextEntry::make('editdate')
                    ->dateTime(),
                TextEntry::make('whatsappparaduvidas'),
                TextEntry::make('permitirinscricao')
                    ->numeric(),
                TextEntry::make('escolhercamisas')
                    ->numeric(),
                TextEntry::make('camisas'),
                TextEntry::make('datacad')
                    ->dateTime(),
                TextEntry::make('infopagamento')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('seguro')
                    ->numeric(),
                TextEntry::make('vlrSeguro')
                    ->numeric(),
                TextEntry::make('combo'),
                TextEntry::make('vlrpago')
                    ->numeric(),
                TextEntry::make('taxaconv')
                    ->numeric(),
                TextEntry::make('vlrTaxaConv')
                    ->numeric(),
                TextEntry::make('ocultarValorCategorias')
                    ->numeric(),
                TextEntry::make('exportarendereco')
                    ->numeric(),
                TextEntry::make('valorfrete')
                    ->numeric(),
                TextEntry::make('emailavisos'),
                TextEntry::make('comissaopagos')
                    ->numeric(),
                TextEntry::make('comissaomarcados')
                    ->numeric(),
                TextEntry::make('comissaocortesia')
                    ->numeric(),
                TextEntry::make('valorPagoTaxas')
                    ->numeric(),
                TextEntry::make('descontartaxasdoliquido')
                    ->numeric(),
                TextEntry::make('qtdPgBoleto')
                    ->numeric(),
                TextEntry::make('qtdPgCartao')
                    ->numeric(),
                TextEntry::make('qtdPgPix')
                    ->numeric(),
                TextEntry::make('qtdPgSaldoPS')
                    ->numeric(),
                TextEntry::make('qtdPgDebOnline')
                    ->numeric(),
                TextEntry::make('qtdPgDepConta')
                    ->numeric(),
                TextEntry::make('qtdMarcadoPago')
                    ->numeric(),
                TextEntry::make('qtdPaidSubscriptions')
                    ->numeric(),
                TextEntry::make('qtdCortesias')
                    ->numeric(),
                TextEntry::make('vlrComissaoTotal')
                    ->numeric(),
                TextEntry::make('custoseguro')
                    ->numeric(),
                TextEntry::make('comissaoreembolsoorg')
                    ->numeric(),
                TextEntry::make('comissaotransferidoevento')
                    ->numeric(),
                TextEntry::make('videoyoutube'),
                TextEntry::make('comissaodivulgador')
                    ->numeric(),
                TextEntry::make('importarFiliados')
                    ->numeric(),
                TextEntry::make('vlrLIberado')
                    ->numeric(),
                TextEntry::make('qtdLiberado')
                    ->numeric(),
                TextEntry::make('vlrTotalLiberado')
                    ->numeric(),
                TextEntry::make('vlrTotalNaoLiberado')
                    ->numeric(),
                TextEntry::make('totalAtletas')
                    ->numeric(),
                TextEntry::make('vltComissaoTotal')
                    ->numeric(),
                TextEntry::make('vlrFinalAPagarOrg')
                    ->numeric(),
                TextEntry::make('qtdPagosLiberados')
                    ->numeric(),
            ]);
    }
}
