<?php

namespace App\Filament\Resources\EventoCupoms\Pages;

use App\Filament\Resources\EventoCupoms\EventoCupomResource;
use Filament\Resources\Pages\CreateRecord;

class CreateEventoCupom extends CreateRecord
{
    protected static string $resource = EventoCupomResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['datacad'] = now()->toDateTimeString();
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
